import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './brand.css';
import './responsive.css';
import './division.css';
import './usage.css';
import './friendly.css';
import './workspace.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
